spring:
  datasource:
    url: jdbc:mysql://moneta.dev.javaloom.com:3306/catalogue_domain
    username: catalogue_user
    password: mspass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
