spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service
          uri: http://catalogue-service:8080
          predicates:
            - Path=/items/**
        - id: orders-service
          uri: http://orders-service:8080
          predicates:
            - Path=/cart/**