### Domain wide properties over all profiles
server:
  forward-headers-strategy: framework
spring:
  profiles:
    include:
      - kafka
      - kubernetes
      - management
      - zipkin
      - zookeeper
      - logging
      - springdoc
inventory:
  uri: http://inventory-service:8080
