spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service
          uri: http://catalogue-service:8080
          predicates:
            - Path=/api/catalogue/v1/**
        - id: catalogue-docs
          uri: http://catalogue-service:8080
          predicates:
            - Path=/doc/catalogue/**
          filters:
            - RewritePath=/doc/catalogue, /swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
            - RewritePath=/doc/catalogue(?<segment>.*), /swagger-ui/$\{segment}
        - id: orders-service
          uri: http://orders-service:8080
          predicates:
            - Path=/api/orders/v1/**
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs