spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service-api
          uri: http://catalogue-service:8080
          predicates:
            - Path=/api/catalogue/v1/**
        - id: catalogue-service
          uri: http://catalogue-service:8080
          predicates:
            - Path=/catalogue/**
          filters:
            - RewritePath=/catalogue/(?<path>.*), /$\{path}

        - id: inventory-service-api
          uri: http://inventory-service:8080
          predicates:
            - Path=/api/inventory/v1/**
        - id: inventory-service
          uri: http://inventory-service:8080
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<path>.*), /$\{path}

        - id: orders-service-api
          uri: http://orders-service:8080
          predicates:
            - Path=/api/orders/v1/**
        - id: orders-service
          uri: http://orders-service:8080
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<path>.*), /$\{path}
        - id: reservations-service-api
          uri: http://reservations-service:8080
          predicates:
            - Path=/api/reservations/v1/**
        - id: reservations-service
          uri: http://reservations-service:8080
          predicates:
            - Path=/reservations/**
          filters:
            - RewritePath=/reservations/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs