spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service
          uri: http://catalogue-service:8080
          predicates:
            - Path=/api/catalogue/v1/**
        - id: catalogue-docs
          uri: http://catalogue-service:8080
          predicates:
            - Path=/doc/catalogue/**
          filters:
            - RewritePath=/doc/catalogue/<path>, /swagger-ui/$\{path}
        - id: orders-service
          uri: http://orders-service:8080
          predicates:
            - Path=/api/orders/v1/**